---
pull_cron_parameters:
  name: "ansible pull config"
  file: "ansible-pull-configs"
  minute: "*/30"
  hour: "*"
  day: "*"
  weekday: "*"
  month: "*"
  user: "root"
  url: "https://github.com/metrika-online/ansible-common.git"

pull_cron_job: "ansible-pull -U {{ pull_cron_parameters.url }} local.yaml --tags=configs"
